Feat/ api 함수 부분적으로 추가
Anifriends/Anifriends-Frontend pull request #46
Opened 2023-11-06 07:47 UTC by DongjaJ

## 📌 이슈번호 

#21

## 📗 구현 내용 

- 일부 api 함수들을 구현했습니다.
- 어떤 api를 했는지 작성하려면 pr이 너무 길어질 것 같아서 노션의 api명세서에 프론트 구현 완료 항목을 체크박스로 확인했습니다
- 우선 이번주 스프린트에 필요해보이는 인증 관련 로직들을 먼저 구현했습니다.

## 📖 구현 스크린샷 
x
## 📖 PR 포인트 & 궁금한 점 
- 너무 많은 api들이 있어서 공통화를 잘 하지 못해 타입이 너무 더러운 것 같습니다...
- 날 잡고 한번 리팩토링을 해야할 것 같지만 일단 구현이 급한 것 같아서 pr을 작성합니다

2023-11-06 09:54 UTC, kutta97 submitted a review, later dismissed
LGTM!

2023-11-06 09:54 UTC, kutta97 commented on packages/shared/apis/shelters/Recruitments.ts
> +};
p5: 만들어주신 타입들은 나중에 의미있게 재사용될 수도 있을 것 같습니다.
추후 리팩토링 때 packages/shared/types/apis/shared/recruitements.ts 로 이동시켜도 좋을 것 같다고 생각하는데, 동환님께서는 어떻게 생각하시나요?

2023-11-06 09:54 UTC, kutta97 commented on packages/shared/apis/shelters/Recruitments.ts
> +type ApplicantStatus = 'PENDING' | 'REFUSED' | 'APPROVED';
p2: 신청현황(신청자수 / 모집인원)을 표현하는 `ApplicantStatus`공통 컴포넌트가 이미 존재해서, 모집현황이라는 의미의 RecruitementStatus 라는 이름으로 바꿔주면 좋을 것 같은데, 동환님께서는 어떻게 생각하시나요?

2023-11-06 18:55 UTC, Eosdia requested changes
동환님 api 작성하시느라 수고많으셨습니다~!

2023-11-08 05:04 UTC, kutta97 commented on packages/shared/apis/common/Auth.ts
> +};
저희 봉사자와 보호소 이메일 중복확인을 따로 해주는 것으로 API 변동 사항이 있었습니다..!ㅠㅠ

2023-11-08 06:03 UTC, kutta97 approved these changes

2023-11-08 06:04 UTC, sukvvon approved these changes
LGTM!! 🙋🏻‍♂️

2023-11-08 06:04 UTC, Eosdia approved these changes
👍👍👍👍👍

2023-11-08 06:05 UTC, merged