fix:공통 레이아웃 컴포넌트 margin 버그 수정 및 리팩토링
Anifriends/Anifriends-Frontend pull request #48
Opened 2023-11-06 09:30 UTC by kutta97

## 📌 이슈번호 

- close #47 

## 📗 구현 내용 
- 공통 레이아웃 컴포넌트의 `width` 가 `maxWidth` 가 되었을때, 알 수 없는 `margin` 이 생기는 버그 수정
- 봉사자앱과 보호소앱의 각 `<Layout/>` 컴포넌트를 공통화하여 shared 로 이동

## 📖 구현 스크린샷 
X

## 📖 PR 포인트 & 궁금한 점

2023-11-06 09:43 UTC, sukvvon commented on packages/shared/layout/index.tsx
> +      <Container maxW="inherit" height="100%" pb="50px" px={0} as="main">
`Container` 내부에 있는 것이므로 `Box` 컴포넌트로 하면 어떨까 하는데 개인적인 취향인 부분일 수 있어서 어떻게 생각하시나요??
만약 `Box` 컴포넌트라면 `px` 속성을 주지 않아도 될 것 같다는 생각이 듭니다!!

2023-11-06 16:49 UTC, Eosdia requested changes

2023-11-06 16:49 UTC, Eosdia commented on packages/shared/layout/index.tsx
> +      <Container maxW="inherit" height="100%" pb="50px" px={0} as="main">
p1: `px ={ 0 }` 이면 저희 좌우여백 16px  이 사라지는데 확인부탁드립니다!!

2023-11-07 04:50 UTC, kutta97 commented on packages/shared/layout/index.tsx
> +      <Container maxW="inherit" height="100%" pb="50px" px={0} as="main">
아, 그 부분은 피그마 디자인을 검토중에, 좌우마진 16px이 불필요한 페이지들이 많이 보여서 임의로 제거했습니다!
ex) 봉사 모집 상세 페이지, 마이페이지, 프로필 페이지, 출석 관리 페이지 등...

2023-11-07 05:08 UTC, kutta97 commented on packages/shared/layout/index.tsx
> +      <Container maxW="inherit" height="100%" pb="50px" px={0} as="main">
아 `Box`가 `Container` 와 달리 기본 스타일 속성이 안붙은 컴포넌트인지 몰랐습니다!
`Box` 컴포넌트로 변경하고, px 속성을 제거한 뒤 `width` 를 100%로 주도록 하겠습니다.

2023-11-07 05:20 UTC, Eosdia approved these changes

2023-11-07 06:43 UTC, merged